server:
  port: 7077
spring:
  application:
    name: hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    hostname: ribbon
    perferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
ribbon:
  eureka:
    enabled: true
    